version: '3.3'
services:
  uptime-kuma:
    restart: always
#   ports:
#     - '3001:3001'
    volumes:
      - '/home/docker/uptime-kuma/data:/app/data'
    container_name: uptime-kuma
    image: 'louislam/uptime-kuma:1'
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true
